list=['Apple','Guava','Mango','Banana','Kiwi']
print("Length of list:",len(list))
print(list[0])
print(list[-1])
list.append('Papaya')
print(list)
list.remove('Mango')
print(list)
list.sort()
print(list)
list.reverse()
print(list)
list.pop(1)
print(list)
print(list*2)
print(list[0:4])
list.clear()
print(list)